version: '2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION      
    volumes:
      - /usr/share/elasticsearch/data      
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"      
    networks:
      - efk         
    logging:
      driver: fluentd
      options:
        fluentd-address: 10.0.75.1:24224
        tag: efk.elasticsearch
  #  depends_on:
  #    - fluentd        
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION        
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - efk
    logging:
      driver: fluentd
      options:
        fluentd-address: 10.0.75.1:24224
        tag: efk.kibana  
#  fluentd:
#    build: 
#      context: ./fluentd
#      args:
#        FLUENTD_VERSION: $FLUENTD_VERSION      
#    volumes:
#      - ./fluentd/conf:/fluentd/etc
#    networks:
#      - efk
#    ports:
#      - "24224:24224"
#      - "24224:24224/udp"
networks:
  efk:
    driver: bridge